version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run:
                name: Build ml-workers Container
                command: |
                    export CONTAINER_NAME=$AWS_ECR_ENDPOINT.dkr.ecr.us-east-1.amazonaws.com/cognoma-ml-workers:$CIRCLE_SHA1
                    docker build -t $CONTAINER_NAME .
            - run:
                name: Test ml-workers
                command: docker run $CONTAINER_NAME python test_ml_task_runner.py
            - deploy:
                name: Deploy Master to ECS
                command: |
                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        chmod +x ecr_push.sh ecs_deploy.sh
                        ./ecr_push.sh
                        ./ecs_deploy.sh --timeout 180 --cluster $AWS_CLUSTER_NAME --service-name $AWS_SERVICE_NAME --image $CONTAINER_NAME
                    fi